### ISSUE TITLE
The "metadata" object should not be required

### ISSUE THREAD

**Issue by balazsdukai** [cityjson/cityjson-qgis-plugin#26]
When loading a file the plugin tries to figure if a file has declared a crs from the presence of the "referenceSystem" key in the "metadata" object. However, if the file doesn't have a crs declared, the "metadata" object might be missing completely, and still be a valid file. See minimal valid CityJSON at  https://www.cityjson.org/specs/1.0.1/#cityjson-object

Currently if "metadata" is not in the file, the plugin returns a KeyError. Instead of KeyError it should set an Undefined CRS in QGIS.

**Comment by liberostelios** [comment]
Problem was fixed, thanks to @Athelena. Will be available on the next release.
