### ISSUE TITLE
Error Installing/Enabling on QGIS 3.10.4-A Coruña 

### ISSUE THREAD

**Issue by chow1026** [cityjson/cityjson-qgis-plugin#29]
I ran into error installing and enabling the cityjson-qgis-plugin on QGIS 3.10.4-A Coruña. Attached screenshot shows the error.

![ErrorEnabling](https://user-images.githubusercontent.com/16604634/80185596-2cbf0800-863f-11ea-8df0-1474dc946c7e.png)

My OS is Ubuntu Bionic 18.04.4 LTS 64bit.

**Comment by liberostelios** [comment]
Is this error still happening? Could you, maybe, start the plugin from the terminal and share the output after this error?

**Comment by chow1026** [comment]
@liberostelios Thank you for your support. I somehow am able to install without error now. Thus, I am closing this issue.
