### ISSUE TITLE
2D and 3D in the 3D-View

### ISSUE THREAD

**Issue by StefanCiesilski** [cityjson/cityjson-qgis-plugin#36]
In the 3D-View i see the 2D ground also.
Is that a setting in QGIS?

![grafik](https://user-images.githubusercontent.com/50232158/116531319-57414200-a8df-11eb-890b-a758ccbec576.png)

**Comment by liberostelios** [comment]
The only way I know of, is to set the 2D symbology to "No Symbols". But this way, you'll have an empty 2D view.

I think you should ask this question at https://github.com/qgis/QGIS, though. It would be nice to have an option to disable the terrain completely (we have an issue with that, here in NL).

**Comment by StefanCiesilski** [comment]
Ticket [https://github.com/qgis/QGIS/issues/43263]
