### ISSUE TITLE
Convert from CityGML bevor use

### ISSUE THREAD

**Issue by StefanCiesilski** [cityjson/cityjson-qgis-plugin#41]
Hi there,
I like to use the plugin with QGIS.
Is it possible to use CityGML data directly. So that they are converted to CityJSON when loading in QGIS?
So far I've always used https://github.com/citygml4j/citygml-tools. Can't be integrated into the plugin because of the java?

thanks
Stefan

**Comment by liberostelios** [comment]
Hi there,

Sorry for the late response. I just realised I missed this issue while I was too busy with other things.

I believe this is out of the context of this plugin. In theory, there is some support for CityGML loading in QGIS directly, although in my experience this is many times problematic (at least last time I checked).

My main concern, though, is that incorporating a whole Java library and tools in the plugin would add too much bloat, so I would refrain for doing so. I'd suggest you keep using this tool before you load your data through this plugin.

Thanks for the suggestion, though.
