### ISSUE TITLE
Qgis crashes

### ISSUE THREAD

**Issue by AdminGeoBim** [cityjson/cityjson-qgis-plugin#51]
Als ik 3D BAG als cityjson .json inlaad crashed Qgis bij het weergeven in 3D zonder melding. Allerlei opties geprobeerd. 
https://youtu.be/9bhy5aeVles

**Comment by liberostelios** [comment]
Hi @AdminGeoBim,

Sorry for the late response. I am not sure why I didn't see this issue so far!

Did you manage to make this work? Maybe if you first load the dataset and then enable the 3D view?

For what is worth, there is also the option to use the [qgs2threejs](https://plugins.qgis.org/plugins/Qgis2threejs/) plugin as an alternative 3D view. In fact, I know that some people prefer it as a viewer to the native 3D map view.

**Comment by lammerts** [comment]
I think this was a issue with my graphic card.
On my new computer no problems. Not crashing.

**Comment by liberostelios** [comment]
Great! Glad to hear all is fixed now. 🙏
